name: example
description: "A fancy button"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  fancy_button:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: AvenirNext
      fonts:
        #AvenirNext-Regular, weight: 400
        - asset: fonts/AvenirNext/avenir-next-regular.woff
        #AvenirNext-Medium, weight: 500
        - asset: fonts/AvenirNext/avenir-next-medium.woff
        #AvenirNext-DemiBold, weight: 600
        - asset: fonts/AvenirNext/avenir-next-demibold.woff
        #AvenirNext-Bold, weight: 700
        - asset: fonts/AvenirNext/avenir-next-bold.woff
        #AvenirNext-Black, weight: 900
        - asset: fonts/AvenirNext/avenir-next-heavy.woff
    - family: AvenirNext-HeavyItalic
      fonts:
        - asset: fonts/AvenirNext-HeavyItalic.ttf