name: fancy_button
description: "Fancy button"
version: 0.0.1
homepage: https://github.com/Code-Cats-Mel/fancy_button

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

